name: pin_field_example
description: Example app demonstrating pin_field_core and pin_field_material packages.
publish_to: 'none'

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pin_field_core:
    path: ../pin_field_core
  pin_field_material:
    path: ../pin_field_material

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
