name: pin_field_core
description: A headless PIN/OTP input engine for Flutter. Zero visual opinion - you build the UI, we handle the input logic.
version: 1.0.0-dev.1
homepage: https://github.com/adar2378/pin_code_fields
repository: https://github.com/adar2378/pin_code_fields/tree/main/packages/pin_field_core

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
