name: pin_code_fields
description: A highly customizable PIN/OTP input field for Flutter with Material Design support and headless core for custom UIs.
version: 9.0.0-dev.1
homepage: https://github.com/adar2378/pin_code_fields
repository: https://github.com/adar2378/pin_code_fields
issue_tracker: https://github.com/adar2378/pin_code_fields/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0